### PR TITLE
Improves CSS for tables

### PR DESCRIPTION
**Pull request by Timothee**
- moves toolbar to bottom of table rather than sidebar
- removes table background and use odd/even selectors on <tr> instead
  (on long tables it would be mismatched)

### CODE REVIEW

**Comment by Timothee** [comment]
Actually it might make more sense to have `#toolbar` inside `#main` but that would change a few more things so I'm sticking to just CSS for now.

**Comment by spect88** [comment]
@Timothee Thanks for the PR!

I've noticed the table row mismatch problem on some systems as well, so I'm perfectly happy with this change.

As for the toolbar, I've deliberately made it separate from the log tables.
Although I understand it's more intuitive for the clear button to be where the table is, the toolbar could (in the future) contain some other buttons which are not related to currently selected menu item.

It would be perfect if chrome.devtools API allowed for adding custom buttons to the toolbar that's already there.
This is not the case, so I've seen 2 possible choices: either make the toolbar full width or place it below the sidebar. I've done the latter thinking that it looks slightly better (double toolbar looks weird) and wastes less screen estate (logs are more important).

**Comment by Timothee** [comment]
What about this instead: a clear button of some kind (the existing icon or something else) that shows up next to each item in the list, on hover. That way it's unobtrusive (doesn't hide the logs) and "localized" (next to the item it refers to). Another benefit is that you can click it without opening that specific log page. It's a benefit for the app I'm working on, because on load we get a whole bunch of events and the panel hangs. (Planning on fixing that too at some point) I've worked around that by deleting the corresponding array from the console...

I'm not sure what you mean by "double toolbar" but that might not be relevant anymore.

What do you think?

**Comment by spect88** [comment]
@Timothee Yeah, it's a good idea with the button on hover. :)

If you could make the css for tables a separate commit, I'd merge it right away.

**Comment by Timothee** [comment]
Hey @spect88, I reverted the changes for the toolbar and made some tiny changes to the CSS. (mostly made the cells wider and removed the 1px top margin on sidebar elements which bothered me so much :))

**Comment by spect88** [comment]
OK, I've pulled the table-related changes: column width and row coloring.
Sorry it took me so much time, I've been busy with other stuff.

The 1px top margin and no _cursor: pointer_ on buttons are supposed to make this extension match Developer Tools look and feel as much as possible. :)

Thanks again for your contribution!

**Comment by Timothee** [comment]
yeah I saw later that the 1px margin is there on the standard panel. Kind of ugly in my opinion. I might have to do a PR on Chromium instead :wink:

**Pull request closed without merging**
